# Generated by Django 6.0.2 on 2026-03-16 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_is_approved'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=255)),
                ('symptoms', models.TextField()),
                ('illness_duration', models.CharField(max_length=100)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='medical_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_reports', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_reports', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PrescribedMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timing', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('medical_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='patients.medicalreport')),
            ],
        ),
    ]
