# Generated by Django 6.0.2 on 2026-03-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='report_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
