# Generated by Django 6.0.2 on 2026-03-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('specialization', models.CharField(choices=[('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Orthopedics', 'Orthopedics'), ('Pediatrics', 'Pediatrics'), ('Gynecology', 'Gynecology'), ('Dermatology', 'Dermatology'), ('Oncology', 'Oncology'), ('Psychiatry', 'Psychiatry'), ('Radiology', 'Radiology'), ('General Practice', 'General Practice'), ('Emergency Medicine', 'Emergency Medicine'), ('Anesthesiology', 'Anesthesiology'), ('Ophthalmology', 'Ophthalmology'), ('ENT', 'ENT (Ear, Nose & Throat)'), ('Urology', 'Urology'), ('Nephrology', 'Nephrology'), ('Gastroenterology', 'Gastroenterology'), ('Endocrinology', 'Endocrinology'), ('Other', 'Other')], max_length=100)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('availability', models.CharField(blank=True, default='', max_length=200)),
                ('bio', models.TextField(blank=True, null=True)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
